// src/pages/compliance-dashboard/components/QuickActions.jsx
import React, { useState } from "react";
import Icon from "../../../components/AppIcon";
import Button from "../../../components/ui/Button";
import PropTypes from "prop-types";

const API_BASE = (import.meta?.env?.VITE_API_URL || "http://localhost:8000").replace(/\/+$/, "");

// Default handlers: note startScan uses camera:open event (UX-first).
const defaultHandlers = {
  async startScan() {
    // Prefer camera/modal flow in UI — open camera modal via event.
    try {
      window.dispatchEvent(new CustomEvent('camera:open'));
      return { ok: true, opened: true };
    } catch (e) {
      // fallback to backend call if event dispatch fails
      const fd = new FormData();
      fd.append("data_source", "manual-dashboard");
      const res = await fetch(`${API_BASE}/scan/start`, { method: "POST", body: fd });
      if (!res.ok) throw new Error(`Scan start failed: ${res.status}`);
      return await res.json();
    }
  },

  async viewRisk() {
    const res = await fetch(`${API_BASE}/scan/status`);
    if (!res.ok) throw new Error("Failed to fetch scan status");
    return await res.json();
  },

  async planRemediation(planIndex = null) {
    const fd = new FormData();
    if (planIndex !== null) fd.append("plan_index", String(planIndex));
    const res = await fetch(`${API_BASE}/remediation/apply`, { method: "POST", body: fd });
    if (!res.ok) throw new Error("Remediation apply failed");
    return await res.json();
  },

  async generateReport({ format = "docx", payload = null } = {}) {
    const fd = new FormData();
    fd.append("format", format === "pdf" ? "pdf" : "docx");
    fd.append("title", "Compliance Report (Quick Action)");
    fd.append("payload_json", JSON.stringify(payload || { summary: "Generated by quick action" }));

    const res = await fetch(`${API_BASE}/reports/generate`, { method: "POST", body: fd });
    if (!res.ok) {
      const txt = await res.text().catch(() => "");
      throw new Error(`Report generation failed: ${res.status} ${txt}`);
    }
    const blob = await res.blob();
    const cd = res.headers?.get?.("content-disposition");
    let filename = `compliance-report.${format === "pdf" ? "pdf" : "docx"}`;
    if (cd) {
      const m = /filename\*=UTF-8''(.+)|filename="?([^";]+)"?/.exec(cd);
      if (m) filename = decodeURIComponent(m[1] || m[2]);
    }
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    return { ok: true, filename };
  }
};

export default function QuickActions({ actions = {}, navigateTo }) {
  const handlers = { ...defaultHandlers, ...actions };
  const [loading, setLoading] = useState(false);

  const quickActions = [
    {
      key: "startScan",
      title: "Start New Scan",
      description: "Initiate comprehensive PII detection across all data sources",
      icon: "Scan",
      action: async () => handlers.startScan(),
      navigateTo: "/data-source-management",
    },
    {
      key: "viewRisk",
      title: "View Risk Details",
      description: "Analyze detailed risk assessments and findings",
      icon: "Shield",
      action: async () => handlers.viewRisk(),
      navigateTo: "/risk-assessment-details",
    },
    {
      key: "planRemediation",
      title: "Plan Remediation",
      description: "Create and manage remediation strategies",
      icon: "CheckCircle",
      action: async () => handlers.planRemediation(),
      navigateTo: "/remediation-planning",
    },
    {
      key: "generateReports",
      title: "Generate Reports",
      description: "Export compliance reports and documentation",
      icon: "FileText",
      action: async () => handlers.generateReport({ format: "docx" }),
      navigateTo: null,
    },
  ];

  const run = async (item) => {
    setLoading(true);
    try {
      const res = await item.action();
      // if the caller requested a navigation path, navigate afterwards
      if (item.navigateTo && typeof navigateTo === "function") {
        navigateTo(item.navigateTo);
      }
      // emit a dashboard-level event so other components can refresh
      try {
        window.dispatchEvent(new CustomEvent("dashboard:refresh", { detail: res }));
      } catch (e) {}
    } catch (err) {
      console.error("Quick action failed", err);
      alert("Action failed: " + (err?.message || err));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-card border border-border rounded-lg p-6">
      <h3 className="text-lg font-semibold text-foreground mb-4">Quick Actions</h3>
      <div className="space-y-3">
        {quickActions.map((act) => (
          <button
            key={act.key}
            onClick={() => run(act)}
            disabled={loading}
            className="w-full p-4 text-left bg-muted/30 hover:bg-muted/50 rounded-lg transition-colors duration-200 group"
          >
            <div className="flex items-start space-x-3">
              <div className={`p-2 rounded-lg bg-muted/10 group-hover:scale-110 transition-transform duration-200`}>
                <Icon name={act.icon} size={18} className="text-primary" />
              </div>
              <div className="flex-1 min-w-0">
                <h4 className="text-sm font-medium text-foreground">{act.title}</h4>
                <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{act.description}</p>
              </div>
              <Icon name="ArrowRight" size={16} className="text-muted-foreground" />
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}

QuickActions.propTypes = {
  actions: PropTypes.object,
  navigateTo: PropTypes.func, // pass useNavigate() from parent
};
